name: 'my first container action'
description: 'Test phase'
author: 'Olawale'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'Awesome Guru'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'

# inputs : data that the action expects to use during runtime, stored as environment variables.
# outputs: output parameters allow you to take actions that have been run previously in the build and output them at the end of the build log
# runs: allows you to choose the type of Github Action we want to use
