on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run the action
      id: anyID
      uses: ./
      with:
        myInput: 'Wale'
    - name: output the memory
      run: |
        echo ${{ steps.anyID.outputs.memory }}
        echo "total memory successfully output"
